---
title: "FinalProjectDraft"
author: "Breanna Schneider, Avery Chan, Maja Velichkovich"
date: "4/1/2021"
output:
  html_document:
    toc: yes
    theme: united
---

# Introduction


# Background 


# Data


# Graphs


# Analysis


# Discussion (Interpretation)


# References 

[Link to Data](https://www.kaggle.com/yamaerenay/spotify-dataset-19212020-160k-tracks)

# Testing code / temporary

```{r setup, include=FALSE, echo = TRUE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
# install.packages(DT)
library(DT)
```

```{r}
genre <- read_csv("data/data_by_genres.csv", col_types = cols())

# glimpse(genre)

x <- genre %>% 
  select(genres) %>% 
  mutate(
    words = str_split(genres, "\\s"),
  )
all_terms <- tibble(term = unlist(x$words, recursive = FALSE))
```

## Top 20 words in genres (to simplify genre categories)

```{r}
# Top terms (double counts...)
genre_term_count <- all_terms %>% 
  group_by(term) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  head(20)

genre_term_count %>% 
  DT::datatable()
```


```{r}
# higher in case when get priority
condensed <- genre %>% 
  mutate(
    simple_genre = case_when(
      str_detect(genres, genre_term_count$term[1]) ~ genre_term_count$term[1],
      str_detect(genres, genre_term_count$term[2]) ~ genre_term_count$term[2],
      str_detect(genres, genre_term_count$term[3]) ~ genre_term_count$term[3],
      str_detect(genres, genre_term_count$term[4]) ~ genre_term_count$term[4],
      str_detect(genres, genre_term_count$term[5]) ~ genre_term_count$term[5],
      str_detect(genres, genre_term_count$term[6]) ~ genre_term_count$term[6],
      str_detect(genres, genre_term_count$term[7]) ~ genre_term_count$term[7],
      str_detect(genres, genre_term_count$term[8]) ~ genre_term_count$term[8],
      str_detect(genres, genre_term_count$term[9]) ~ genre_term_count$term[9],
      str_detect(genres, genre_term_count$term[10]) ~ genre_term_count$term[10],
      str_detect(genres, genre_term_count$term[11]) ~ genre_term_count$term[11],
      str_detect(genres, genre_term_count$term[12]) ~ genre_term_count$term[12],
      str_detect(genres, genre_term_count$term[13]) ~ genre_term_count$term[13],
      str_detect(genres, genre_term_count$term[14]) ~ genre_term_count$term[14],
      str_detect(genres, genre_term_count$term[15]) ~ genre_term_count$term[15],
      str_detect(genres, genre_term_count$term[16]) ~ genre_term_count$term[16],
      str_detect(genres, genre_term_count$term[17]) ~ genre_term_count$term[17],
      str_detect(genres, genre_term_count$term[18]) ~ genre_term_count$term[18],
      str_detect(genres, genre_term_count$term[19]) ~ genre_term_count$term[19],
      str_detect(genres, genre_term_count$term[20]) ~ genre_term_count$term[20],
      TRUE ~ "other"
    )
  )

condensed %>% 
  group_by(simple_genre) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  DT::datatable()
```

## Test graphs of condensed genres

```{r}
condensed %>% 
  group_by(simple_genre) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  ggplot(aes(y = simple_genre, x = n)) +
  geom_col()

condensed %>% 
  ggplot(aes(y = simple_genre, x = instrumentalness)) +
  geom_point()

condensed %>%
  select(simple_genre, instrumentalness) %>% 
  group_by(simple_genre) %>%
  summarise(mean_inst = mean(instrumentalness)) %>% 
  ggplot(aes(y = simple_genre, x = mean_inst)) +
  geom_col()

condensed %>%
  ggplot(aes(y = simple_genre, x = danceability)) +
  geom_boxplot()
```

## All possible graphs of feature v feature

```{r}
# for (var_name in colnames(year)[2:12]) {
#   condensed %>%
#     ggplot(aes(y = simple_genre, x = get(condensed, var_name))) +
#     geom_boxplot() %>%
#     print()
# }

```

## All r-values

```{r}
year <- read_csv("data/data_by_year.csv", col_types = cols())

# All r values
year %>% 
  select(-c(year, key, mode)) %>% 
  cor() %>% 
  round(digits = 2) %>% 
  data.frame() %>% 
  DT::datatable()
```

## Displaying all r-values

```{r}
# All graphs
# for (a in colnames(year)[2:12]) {
#   for (b in colnames(year)[2:12]) {
#     if (a > b) {
#       g <- year %>%
#         summarise(
#           a_var = get(a),
#           b_var = get(b)
#         ) %>% 
#         ggplot(aes(x = a_var, y = b_var)) +
#         geom_point() +
#         labs(
#           x = a,
#           y = b
#           )
#       print(g)
#     }
#   }
# }

# https://statsandr.com/blog/correlation-coefficient-and-correlation-test-in-r/

pairs(year[,c(5, 2, 7, 8)])

pairs(year[2:12])

# combn(colnames(year)[2:12], 2)
```

```{r}
# > install.packages("corrplot")
library(corrplot)

# year %>% glimpse()

year <- year %>% 
  rename(
    yr = year,
    ac = acousticness,
    db = danceability,
    dur = duration_ms,
    en = energy,
    ins = instrumentalness,
    li = liveness,
    lo = loudness,
    sp = speechiness,
    tmp = tempo,
    val = valence,
    pop = popularity,
    k = key,
    m = mode
  )
```


```{r}
corrplot(
  round(cor(year[2:12]), 1),
  method = "number",
  type = "upper" # show only upper side
)

corrplot(
  round(cor(year[2:12]), 1),
  method = "color",
  type = "upper" # show only upper side
)

corrplot.mixed(
  round(cor(year[2:12]), 1),
  lower = "number",
  upper = "color"
)

corrplot(cor(year[,c(5, 2, 7, 8)]),
  method = "number",
  type = "upper" # show only upper side
)
```
